---
abstract: 'An interesting approach to localize concise time duration string representation.'
author:
  - 'Binary.com <perl@binary.com>'
build_requires:
  Carp: '0'
  Module::Runtime: '0'
  Moo: '0'
  POSIX: '0'
  Test::Exception: '0'
  Test::FailWarnings: '0'
  Test::More: '0'
  Time::Seconds: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.141520'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Time-Duration-Concise-Localize
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.006'
version: '0.02'
