---
abstract: 'localize concise time duration string representation.'
author:
  - 'Binary.com <perl@binary.com>'
build_requires:
  Module::Pluggable: '0'
  Test::Exception: '0'
  Test::FailWarnings: '0'
  Test::More: '0'
  Test::NoWarnings: '0'
  Time::Seconds: '1.27'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.141520'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Time-Duration-Concise-Localize
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Module::Pluggable: '0'
  POSIX: '0'
  Tie::Hash::LRU: '0'
  Time::Seconds: '1.27'
  perl: '5.006'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Time-Duration-Concise-Localize
  homepage: https://github.com/binary-com/perl-Time-Duration-Concise-Localize
version: '1.9'
